const inventoryData = [
  {
    item: "T Shirt",
    location_id: "1",
    safety_stock: "200",
    reorder_point: "300",
    quantity_on_hand: "250",
    average_usage: "20",
    lead_time: "10",
  },
  {
    item: "Hoodie",
    location_id: "1",
    safety_stock: "500",
    reorder_point: "700",
    quantity_on_hand: "150",
    average_usage: "10",
    lead_time: "10",
  },
  {
    item: "Jeans",
    location_id: "1",
    safety_stock: "300",
    reorder_point: "600",
    quantity_on_hand: "100",
    average_usage: "15",
    lead_time: "10",
  },
  {
    item: "Sneakers",
    location_id: "1",
    safety_stock: "100",
    reorder_point: "200",
    quantity_on_hand: "10",
    average_usage: "25",
    lead_time: "10",
  },
  {
    item: "Socks",
    location_id: "1",
    safety_stock: "1000",
    reorder_point: "1500",
    quantity_on_hand: "250",
    average_usage: "30",
    lead_time: "10",
  },
  {
    item: "Chino",
    location_id: "1",
    safety_stock: "500",
    reorder_point: "1000",
    quantity_on_hand: "100",
    average_usage: "10",
    lead_time: "10",
  },
];
